### ISSUE TITLE
Sources Checklist

### ISSUE THREAD

**Issue by jakiestfu** [jakiestfu/trill#1]
### Subscription Music Services
- [ ] Spotify
- [ ] Beats Music
- [ ] Google Play Music (on-demand streaming and music locker)
- [ ] TIDAL
- [ ] Rdio (Android only)
- [ ] Deezer (Android only)
### Free Streaming/Music Promotion Platforms
- [ ] Soundcloud
- [ ] YouTube
- [ ] Vimeo
- [ ] Last.fm
- [ ] Bandcamp
- [ ] Official.fm
- [ ] Jamendo
### Network/Cloud storage
- [ ] Ampache
- [ ] Owncloud
- [ ] Subsonic
- [ ] Beets
### Misc
- [ ] Generic Audio Files (mp3, wav, mpg)
